spring:
  application:
    name: spring-boot
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

 # 日志
logging:
  config: classpath:log4j2.yml
  level:
     org.springframework: info